import { Metadata } from 'next';
import AdminDashboardLayout from './admin-dashboard-layout';
import { Toaster } from '@/components/ui/toaster';
export const metadata: Metadata = {
  title: 'YOUR APP NAME | App description',
  description: 'Generated by create next app',
};
export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminDashboardLayout>
      {children}
      <Toaster />
    </AdminDashboardLayout>
  );
}
