import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* Header */}
      <div className="mx-auto min-h-screen max-w-6xl bg-white">{children}</div>
      {/* Footer */}
    </div>
  );
}
